### ISSUE TITLE
GO won't install the package

### ISSUE THREAD

**Issue by clenio** [juniorgarcia/ascii-banner-cli#1]
get or install messages return nothing.

GO Version: go1.15.6 linux/amd64

![pic-selected-201231-1025-25](https://user-images.githubusercontent.com/2649760/103412209-c20d8700-4b52-11eb-934c-f847d02fc251.png)

**Comment by juniorgarcia** [comment]
My mistake. Your `$PATH` variable should include the `bin` folder which is on your `$GOPATH`?

Suppose you're using bash, you should add this on your `~/.bashrc`

```
export PATH="$GOPATH/bin:$PATH"
```

Then you should restart the terminal, or run `source ~/.bashrc`.

This should do it. I'm going to update the README.md with this information.

**Comment by clenio** [comment]
Works, thancks!
